# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: cognicity-statistics # NOTE: update this with your service name

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
# frameworkVersion: "=X.X.X"

provider:
  name: aws
  runtime: nodejs6.10
  stackTags:
    area: ${file(./tags.yml):area}

# you can overwrite defaults here
  stage: prod
  region: ap-southeast-1

functions:
  reportsSummary:
    handler: reportsSummary.handler
    environment:
      BASE_URL: data.petabencana.id
    events:
      - http:
          path: reportsSummary
          method: get
          cors: true

  floodedRegionsSummary:
    handler: floodedRegionsSummary.handler
    environment:
      BASE_URL: data.petabencana.id
    events:
      - http:
          path: floodedRegionsSummary
          method: get
          cors: true
  floodedRWsSummary:
    handler: floodedRWsSummary.handler
    environment:
      BASE_URL: data.petabencana.id
    events:
      - http:
          path: floodedRWsSummary
          method: get
          cors: true
